-- ==============================================================================
-- 01_core_tables.sql
-- Plataforma LEMMAS (Powered by MathAI Engine)
-- Camada 1: Observed Data (Core Entities & Learning State)
-- ==============================================================================

-- 1. TABELA: usuarios
-- Armazena os perfis de estudantes e professores da plataforma.
CREATE TABLE IF NOT EXISTS public.usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    senha_hash TEXT NOT NULL,
    cpf TEXT,
    idade INTEGER CHECK (idade >= 5 AND idade <= 120),
    celular TEXT,
    cep TEXT,
    logradouro TEXT,
    numero TEXT,
    bairro TEXT,
    cidade TEXT,
    estado TEXT,
    motivos TEXT,
    escolaridade TEXT,
    faculdade TEXT,
    curso TEXT,
    concursos_foco TEXT,
    verificado INTEGER NOT NULL DEFAULT 0,
    criado_em TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_usuarios_email ON public.usuarios USING btree (email);

-- 2. TABELA: questoes
-- Acervo de itens matemáticos estruturados com metadados didáticos e LaTeX.
CREATE TABLE IF NOT EXISTS public.questoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    materia TEXT NOT NULL,
    topico TEXT NOT NULL,
    subtopico TEXT,
    dificuldade INTEGER CHECK (dificuldade IS NULL OR (dificuldade >= 1 AND dificuldade <= 5)),
    banca TEXT,
    ano INTEGER,
    enunciado TEXT NOT NULL,
    figura_path TEXT,
    gabarito TEXT,
    estrategias_esperadas TEXT,
    tipo TEXT NOT NULL DEFAULT 'objetiva' CHECK (tipo IN ('objetiva', 'discursiva')),
    criado_em TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_questoes_materia_topico ON public.questoes USING btree (materia, topico);

-- 3. TABELA: conceitos (Lemas & Teoremas)
-- Banco de lemas para consulta socrática e flashcards ativos.
CREATE TABLE IF NOT EXISTS public.conceitos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    materia TEXT NOT NULL,
    topico TEXT NOT NULL,
    nome TEXT NOT NULL,
    gatilho TEXT NOT NULL,
    acao_ou_teorema TEXT NOT NULL,
    formula_latex TEXT,
    criado_em TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

-- 4. TABELA: tentativas
-- Registro empírico factual de cada resolução submetida pelo aluno.
CREATE TABLE IF NOT EXISTS public.tentativas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    questao_id BIGINT NOT NULL REFERENCES public.questoes(id) ON DELETE CASCADE,
    aluno_id BIGINT NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
    data_hora TIMESTAMPTZ DEFAULT timezone('utc'::text, now()),
    tempo_segundos INTEGER NOT NULL CHECK (tempo_segundos >= 0),
    acertou INTEGER NOT NULL CHECK (acertou IN (0, 1)),
    estrategia_usada TEXT,
    tipo_erro TEXT DEFAULT 'nenhum' CHECK (
        tipo_erro IN ('nenhum', 'conta_sinal', 'manipulacao_algebrica', 'conceitual', 'interpretacao', 'outro', 'simulado_incorreto')
    ),
    confianca_aluno INTEGER CHECK (confianca_aluno BETWEEN 1 AND 5),
    anotacoes TEXT,
    imagem_resolucao_path TEXT
);

CREATE INDEX IF NOT EXISTS idx_tentativas_aluno ON public.tentativas USING btree (aluno_id);
CREATE INDEX IF NOT EXISTS idx_tentativas_questao_id ON public.tentativas USING btree (questao_id);
CREATE INDEX IF NOT EXISTS idx_tentativas_data ON public.tentativas USING btree (data_hora);

-- 5. TABELA: revisao_espacada
-- Motor determinístico SM-2 agnóstico a disciplinas para agendamento de repetição espaçada.
CREATE TABLE IF NOT EXISTS public.revisao_espacada (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aluno_id BIGINT NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
    item_tipo TEXT NOT NULL CHECK (item_tipo IN ('questao', 'conceito')),
    item_id BIGINT NOT NULL,
    fator_facilidade REAL DEFAULT 2.5 CHECK (fator_facilidade >= 1.3),
    intervalo_dias INTEGER DEFAULT 1 CHECK (intervalo_dias >= 1),
    repeticoes INTEGER DEFAULT 0 CHECK (repeticoes >= 0),
    proxima_revisao DATE NOT NULL,
    ultima_revisao TIMESTAMPTZ DEFAULT timezone('utc'::text, now()),
    CONSTRAINT revisao_espacada_aluno_id_item_tipo_item_id_key UNIQUE (aluno_id, item_tipo, item_id)
);

CREATE INDEX IF NOT EXISTS idx_revisao_aluno ON public.revisao_espacada USING btree (aluno_id, proxima_revisao);

-- ==============================================================================
-- SEGURANÇA & ROW LEVEL SECURITY (RLS)
-- ==============================================================================

ALTER TABLE public.usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.questoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conceitos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tentativas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.revisao_espacada ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'usuarios' AND policyname = 'Acesso usuarios') THEN
        CREATE POLICY "Acesso usuarios" ON public.usuarios FOR ALL TO public USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'questoes' AND policyname = 'Leitura pública de questoes') THEN
        CREATE POLICY "Leitura pública de questoes" ON public.questoes FOR SELECT TO public USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'conceitos' AND policyname = 'Leitura pública de conceitos') THEN
        CREATE POLICY "Leitura pública de conceitos" ON public.conceitos FOR SELECT TO public USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'tentativas' AND policyname = 'Acesso tentativas') THEN
        CREATE POLICY "Acesso tentativas" ON public.tentativas FOR ALL TO public USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'revisao_espacada' AND policyname = 'Acesso revisao_espacada') THEN
        CREATE POLICY "Acesso revisao_espacada" ON public.revisao_espacada FOR ALL TO public USING (true) WITH CHECK (true);
    END IF;
END $$;

-- Concessão de privilégios para roles da API PostgREST / Supabase
GRANT SELECT, INSERT, UPDATE, DELETE ON public.usuarios TO anon, authenticated, service_role;
GRANT SELECT ON public.questoes TO anon, authenticated, service_role;
GRANT SELECT ON public.conceitos TO anon, authenticated, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.tentativas TO anon, authenticated, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.revisao_espacada TO anon, authenticated, service_role;
