-- ==============================================================================
-- 02_provenance_and_consent.sql
-- Plataforma LEMMAS (Powered by MathAI Engine)
-- Camadas 2 & 3: Proveniência, Consentimento e Validação Humana
-- Princípio Arquitetural: OBSERVED DATA != AI INTERPRETATION != VALIDATED LABEL
-- ==============================================================================

-- 1. TABELA: consentimentos (LGPD & Governança de Dados)
-- Registra as permissões explícitas e granulares concedidas pelo estudante.
CREATE TABLE IF NOT EXISTS public.consentimentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aluno_id BIGINT NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
    versao_consentimento TEXT NOT NULL DEFAULT 'v1.0',
    coleta_dados BOOLEAN NOT NULL DEFAULT true,
    processamento_ia BOOLEAN NOT NULL DEFAULT true,
    uso_pesquisa BOOLEAN NOT NULL DEFAULT false,
    treinamento_modelos BOOLEAN NOT NULL DEFAULT false,
    aceito_em TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    revogado_em TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_consentimentos_aluno_id ON public.consentimentos USING btree (aluno_id);
CREATE INDEX IF NOT EXISTS idx_consentimentos_aluno_ativo ON public.consentimentos USING btree (aluno_id) WHERE revogado_em IS NULL;

-- 2. TABELA: avaliacoes_ia (AI Interpretation)
-- Rastreabilidade estrita de cada inferência dos modelos da MathAI Engine.
CREATE TABLE IF NOT EXISTS public.avaliacoes_ia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tentativa_id BIGINT NOT NULL REFERENCES public.tentativas(id) ON DELETE CASCADE,
    provedor_modelo TEXT NOT NULL,
    nome_modelo TEXT NOT NULL,
    versao_modelo TEXT,
    versao_prompt TEXT NOT NULL,
    fallback_level INTEGER NOT NULL DEFAULT 0 CHECK (fallback_level >= 0),
    latencia_ms INTEGER CHECK (latencia_ms IS NULL OR latencia_ms >= 0),
    input_hash TEXT,
    output_raw TEXT,
    output_estruturado JSONB NOT NULL DEFAULT '{}'::jsonb,
    confianca REAL CHECK (confianca IS NULL OR (confianca >= 0.0 AND confianca <= 1.0)),
    criado_em TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_avaliacoes_ia_tentativa_id ON public.avaliacoes_ia USING btree (tentativa_id);
CREATE INDEX IF NOT EXISTS idx_avaliacoes_ia_input_hash ON public.avaliacoes_ia USING btree (input_hash);
CREATE INDEX IF NOT EXISTS idx_avaliacoes_ia_modelo ON public.avaliacoes_ia USING btree (provedor_modelo, nome_modelo);
CREATE INDEX IF NOT EXISTS idx_avaliacoes_ia_criado_em ON public.avaliacoes_ia USING btree (criado_em);
CREATE INDEX IF NOT EXISTS idx_avaliacoes_ia_output_gin ON public.avaliacoes_ia USING gin (output_estruturado);

-- 3. TABELA: feedback_tentativa (Human-in-the-Loop: Aluno)
-- Retorno imediato do estudante sobre a utilidade e acurácia do parecer da IA.
CREATE TABLE IF NOT EXISTS public.feedback_tentativa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tentativa_id BIGINT NOT NULL REFERENCES public.tentativas(id) ON DELETE CASCADE,
    avaliacao_ia_id BIGINT REFERENCES public.avaliacoes_ia(id) ON DELETE SET NULL,
    util BOOLEAN NOT NULL,
    concorda_diagnostico BOOLEAN NOT NULL,
    comentario_aluno TEXT,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_feedback_tentativa_tentativa_id ON public.feedback_tentativa USING btree (tentativa_id);
CREATE INDEX IF NOT EXISTS idx_feedback_tentativa_avaliacao_id ON public.feedback_tentativa USING btree (avaliacao_ia_id);

-- 4. TABELA: validacao_humana (Validated Label: Curadoria Pedagógica Especializada)
-- Padrão-ouro (Ground Truth Aferido) por professor/especialista para treino de modelos.
CREATE TABLE IF NOT EXISTS public.validacao_humana (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tentativa_id BIGINT NOT NULL REFERENCES public.tentativas(id) ON DELETE CASCADE,
    validador_id BIGINT NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
    erro_validado TEXT,
    conceito_validado TEXT,
    status_validacao TEXT NOT NULL CHECK (status_validacao IN ('aprovado_treino', 'ambiguo', 'rejeitado')),
    validado_em TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_validacao_humana_tentativa_id ON public.validacao_humana USING btree (tentativa_id);
CREATE INDEX IF NOT EXISTS idx_validacao_humana_validador_id ON public.validacao_humana USING btree (validador_id);
CREATE INDEX IF NOT EXISTS idx_validacao_humana_status ON public.validacao_humana USING btree (status_validacao);

-- ==============================================================================
-- SEGURANÇA & ROW LEVEL SECURITY (RLS)
-- ==============================================================================

ALTER TABLE public.consentimentos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.avaliacoes_ia ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.feedback_tentativa ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.validacao_humana ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'consentimentos' AND policyname = 'Acesso consentimentos') THEN
        CREATE POLICY "Acesso consentimentos" ON public.consentimentos FOR ALL TO public USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'avaliacoes_ia' AND policyname = 'Acesso avaliacoes_ia') THEN
        CREATE POLICY "Acesso avaliacoes_ia" ON public.avaliacoes_ia FOR ALL TO public USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'feedback_tentativa' AND policyname = 'Acesso feedback_tentativa') THEN
        CREATE POLICY "Acesso feedback_tentativa" ON public.feedback_tentativa FOR ALL TO public USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'validacao_humana' AND policyname = 'Acesso validacao_humana') THEN
        CREATE POLICY "Acesso validacao_humana" ON public.validacao_humana FOR ALL TO public USING (true) WITH CHECK (true);
    END IF;
END $$;

-- Concessão de privilégios para roles da API PostgREST / Supabase
GRANT SELECT, INSERT, UPDATE, DELETE ON public.consentimentos TO anon, authenticated, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.avaliacoes_ia TO anon, authenticated, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.feedback_tentativa TO anon, authenticated, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.validacao_humana TO anon, authenticated, service_role;
