-- Table: flashcards
CREATE TABLE IF NOT EXISTS public.flashcards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id TEXT NOT NULL,
    card_type VARCHAR(20) NOT NULL CHECK (card_type IN ('formula', 'concept', 'recognition', 'application', 'error_recall', 'diagram')),
    front TEXT NOT NULL,
    back TEXT NOT NULL,
    source_type VARCHAR(20) NOT NULL CHECK (source_type IN ('ai_generated', 'student_created', 'teacher_created', 'imported_anki')),
    source_id BIGINT,
    concept_id BIGINT,
    status VARCHAR(20) NOT NULL DEFAULT 'inbox_pending' CHECK (status IN ('inbox_pending', 'approved', 'discarded')),
    generator_model VARCHAR,
    generator_prompt_version VARCHAR,
    student_edited BOOLEAN DEFAULT FALSE,
    fsrs_stability FLOAT DEFAULT 2.0,
    fsrs_difficulty FLOAT DEFAULT 5.0,
    fsrs_reps INTEGER DEFAULT 0,
    fsrs_lapses INTEGER DEFAULT 0,
    fsrs_state VARCHAR(20) DEFAULT 'new' CHECK (fsrs_state IN ('new', 'learning', 'review')),
    due_date TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

-- Indexes for flashcards
CREATE INDEX IF NOT EXISTS idx_flashcards_student_id ON public.flashcards(student_id);
CREATE INDEX IF NOT EXISTS idx_flashcards_status ON public.flashcards(status);
CREATE INDEX IF NOT EXISTS idx_flashcards_due_date ON public.flashcards(due_date) WHERE due_date IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_flashcards_card_type ON public.flashcards(card_type);
CREATE INDEX IF NOT EXISTS idx_flashcards_source_type ON public.flashcards(source_type);

-- Table: card_reviews
CREATE TABLE IF NOT EXISTS public.card_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_id BIGINT NOT NULL REFERENCES public.flashcards(id) ON DELETE CASCADE,
    student_id TEXT NOT NULL,
    reviewed_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()),
    rating INTEGER NOT NULL CHECK (rating IN (1, 2, 3, 4)),
    response_time_ms INTEGER,
    was_correct BOOLEAN NOT NULL,
    scheduler VARCHAR DEFAULT 'FSRS-v4',
    scheduler_version VARCHAR DEFAULT '1.0',
    previous_interval INTEGER DEFAULT 0,
    new_interval INTEGER DEFAULT 0
);

-- Indexes for card_reviews
CREATE INDEX IF NOT EXISTS idx_card_reviews_card_id ON public.card_reviews(card_id);
CREATE INDEX IF NOT EXISTS idx_card_reviews_student_id ON public.card_reviews(student_id);
CREATE INDEX IF NOT EXISTS idx_card_reviews_reviewed_at ON public.card_reviews(reviewed_at);

-- Row Level Security (RLS)
ALTER TABLE public.flashcards ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.card_reviews ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'flashcards' AND policyname = 'Acesso flashcards') THEN
        CREATE POLICY "Acesso flashcards" ON public.flashcards FOR ALL TO public USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'card_reviews' AND policyname = 'Acesso card_reviews') THEN
        CREATE POLICY "Acesso card_reviews" ON public.card_reviews FOR ALL TO public USING (true) WITH CHECK (true);
    END IF;
END $$;