UPDATE questoes SET subtopico = 'Adição de Frações com Denominadores Iguais', dificuldade = 1 WHERE id = 1452;
UPDATE questoes SET subtopico = 'Adição de Frações com Denominadores Diferentes', dificuldade = 2 WHERE id = 1453;
UPDATE questoes SET subtopico = 'Adição de Frações com Denominadores Iguais', dificuldade = 1 WHERE id = 1454;
UPDATE questoes SET subtopico = 'Soma de Frações Algébricas', dificuldade = 3 WHERE id = 1455;
UPDATE questoes SET subtopico = 'Soma de Frações Algébricas', dificuldade = 3 WHERE id = 1456;
UPDATE questoes SET subtopico = 'Relação Fundamental da Trigonometria', dificuldade = 3 WHERE id = 1457;
UPDATE questoes SET subtopico = 'Soma de Frações Algébricas', dificuldade = 3 WHERE id = 1474;
UPDATE questoes SET subtopico = 'Relação de Euler em Poliedros', dificuldade = 2 WHERE id = 1461;
UPDATE questoes SET subtopico = 'Poliedros Estrelados', dificuldade = 3 WHERE id = 1462;
UPDATE questoes SET subtopico = 'Geometria Espacial no Cotidiano', dificuldade = 2 WHERE id = 1463;
UPDATE questoes SET subtopico = 'Sólidos de Revolução', dificuldade = 2 WHERE id = 1464;
UPDATE questoes SET subtopico = 'Fórmula de Bhaskara', dificuldade = 2 WHERE id = 1465;
UPDATE questoes SET subtopico = 'Relações de Girard', dificuldade = 2 WHERE id = 1466;
UPDATE questoes SET subtopico = 'Operações com Vetores', dificuldade = 3 WHERE id = 1467;
UPDATE questoes SET subtopico = 'Combinação Linear e Módulo de Vetores', dificuldade = 4 WHERE id = 1468;
UPDATE questoes SET subtopico = 'Conversão de Gramas para Quilogramas', dificuldade = 1 WHERE id = 1469;
UPDATE questoes SET subtopico = 'Conversão de Gramas para Miligramas', dificuldade = 1 WHERE id = 1470;
UPDATE questoes SET subtopico = 'Adição de Frações com Denominadores Iguais', dificuldade = 1 WHERE id = 1471;
UPDATE questoes SET subtopico = 'Adição de Frações com Denominadores Diferentes', dificuldade = 2 WHERE id = 1472;
UPDATE questoes SET subtopico = 'Adição de Frações com Denominadores Iguais', dificuldade = 1 WHERE id = 1473;
UPDATE questoes SET subtopico = 'Soma de Frações Algébricas', dificuldade = 3 WHERE id = 1475;
UPDATE questoes SET subtopico = 'Identidades Trigonométricas Fundamentais', dificuldade = 3 WHERE id = 1476;
UPDATE questoes SET subtopico = 'Continuidade de Funções em um Ponto', dificuldade = 3 WHERE id = 1488;
UPDATE questoes SET subtopico = 'Continuidade com Funções Definidas por Sentenças', dificuldade = 4 WHERE id = 1489;
UPDATE questoes SET subtopico = 'Limites com Indeterminação 0/0', dificuldade = 3 WHERE id = 1490;
UPDATE questoes SET subtopico = 'Limites no Infinito de Funções Racionais', dificuldade = 3 WHERE id = 1491;
UPDATE questoes SET subtopico = 'Limites no Infinito de Funções Racionais', dificuldade = 3 WHERE id = 1492;
UPDATE questoes SET subtopico = 'Limites com Radical e Racionalização', dificuldade = 4 WHERE id = 1493;
UPDATE questoes SET subtopico = 'Cálculo de Limites por Substituição Direta', dificuldade = 1 WHERE id = 1494;
UPDATE questoes SET subtopico = 'Cálculo de Limites de Funções Racionais', dificuldade = 2 WHERE id = 1495;
UPDATE questoes SET subtopico = 'Limites Envolvendo Radicais', dificuldade = 4 WHERE id = 1496;
UPDATE questoes SET subtopico = 'Equação do 2º Grau por Bhaskara', dificuldade = 2 WHERE id = 1497;
UPDATE questoes SET subtopico = 'Equação do 2º Grau por Soma e Produto', dificuldade = 2 WHERE id = 1498;
UPDATE questoes SET subtopico = 'Completamento de Quadrados', dificuldade = 3 WHERE id = 1499;