UPDATE questoes SET materia = 'Álgebra', topico = 'Progressões', subtopico = 'Progressão Aritmética (PA)' WHERE id = 1247;
UPDATE questoes SET materia = 'Matemática Financeira', topico = 'SAC', subtopico = 'Sistema de Amortização Constante' WHERE id = 1248;
UPDATE questoes SET materia = 'Polinômios e Complexos', topico = 'Polinômios', subtopico = 'Raízes Reais e Complexas' WHERE id = 1249;
UPDATE questoes SET materia = 'Álgebra', topico = 'Funções', subtopico = 'Injetividade, Sobrejetividade e Imagem' WHERE id = 1250;
UPDATE questoes SET materia = 'Cálculo', topico = 'Integrais', subtopico = 'Comprimento de Arco' WHERE id = 1251;
UPDATE questoes SET materia = 'Cálculo', topico = 'Integrais', subtopico = 'Volume de Sólidos de Revolução e Criptas' WHERE id = 1252;
UPDATE questoes SET materia = 'Álgebra Linear', topico = 'Autovalores', subtopico = 'Autovalores e Matrizes' WHERE id = 1253;
UPDATE questoes SET materia = 'Probabilidade e Estatística', topico = 'Estatística', subtopico = 'Média, Variância, Mediana e Moda' WHERE id = 1254;
UPDATE questoes SET materia = 'Geometria Espacial', topico = 'Esferas', subtopico = 'Esfera inscrita em Cilindro e Cones' WHERE id = 1255;
UPDATE questoes SET materia = 'Cálculo', topico = 'Taxas Relacionadas', subtopico = 'Taxas Relacionadas em Cones' WHERE id = 1256;
UPDATE questoes SET materia = 'Cálculo', topico = 'Derivadas', subtopico = 'Otimização e Aplicações da Derivada' WHERE id = 1257;
UPDATE questoes SET materia = 'Álgebra', topico = 'Progressões', subtopico = 'Relações entre PA e PG' WHERE id = 1258;
UPDATE questoes SET materia = 'Cálculo', topico = 'Integrais', subtopico = 'Cálculo de Área entre Curvas' WHERE id = 1259;
UPDATE questoes SET materia = 'Geometria Analítica', topico = 'Cônicas', subtopico = 'Hipérbole e Circunferência' WHERE id = 1260;
UPDATE questoes SET materia = 'Álgebra Linear', topico = 'Determinantes', subtopico = 'Matrizes e Invertibilidade' WHERE id = 1261;
UPDATE questoes SET materia = 'Álgebra', topico = 'Progressões', subtopico = 'Progressão Geométrica (PG) e Frações' WHERE id = 1262;
UPDATE questoes SET materia = 'Matemática Financeira', topico = 'Juros Compostos', subtopico = 'Financiamentos e Parcelamentos' WHERE id = 1263;
UPDATE questoes SET materia = 'Geometria Analítica', topico = 'Retas', subtopico = 'Geometria Analítica no Espaço' WHERE id = 1264;
UPDATE questoes SET materia = 'Probabilidade e Estatística', topico = 'Estatística', subtopico = 'Análise de Dados Amostrais' WHERE id = 1265;
UPDATE questoes SET materia = 'Cálculo', topico = 'Derivadas', subtopico = 'Modelagem Matemática e Simulação' WHERE id = 1266;
UPDATE questoes SET materia = 'Probabilidade e Estatística', topico = 'Estatística', subtopico = 'Medidas de tendência central e dispersão' WHERE id = 1267;
UPDATE questoes SET materia = 'Cálculo', topico = 'Derivadas', subtopico = 'Taxas relacionadas' WHERE id = 1268;
UPDATE questoes SET materia = 'Álgebra', topico = 'Progressões', subtopico = 'Sequências e recorrências' WHERE id = 1269;
UPDATE questoes SET materia = 'Geometria Plana', topico = 'Triângulos', subtopico = 'Áreas de triângulos e relações métricas' WHERE id = 1270;
UPDATE questoes SET materia = 'Geometria Analítica', topico = 'Cônicas', subtopico = 'Distância de ponto a curva e lugares geométricos' WHERE id = 1271;
UPDATE questoes SET materia = 'Cálculo', topico = 'Integrais', subtopico = 'Volume de sólidos de revolução' WHERE id = 1272;
UPDATE questoes SET materia = 'Álgebra', topico = 'Progressões', subtopico = 'Modelagem algébrica e sequências' WHERE id = 1273;
UPDATE questoes SET materia = 'Cálculo', topico = 'Derivadas', subtopico = 'Problemas de otimização' WHERE id = 1274;
UPDATE questoes SET materia = 'Polinômios e Complexos', topico = 'Números Complexos', subtopico = 'Forma trigonométrica e Teorema de De Moivre' WHERE id = 1275;
UPDATE questoes SET materia = 'Geometria Espacial', topico = 'Prismas', subtopico = 'Áreas e volumes de prismas retos' WHERE id = 1276;
UPDATE questoes SET materia = 'Probabilidade e Estatística', topico = 'Combinatória', subtopico = 'Teoria dos conjuntos e princípio inclusão-exclusão' WHERE id = 1277;
UPDATE questoes SET materia = 'Trigonometria', topico = 'Identidades', subtopico = 'Relações trigonométricas para arcos notáveis' WHERE id = 1278;
UPDATE questoes SET materia = 'Geometria Analítica', topico = 'Retas', subtopico = 'Equação da reta e propriedades do paralelogramo' WHERE id = 1279;
UPDATE questoes SET materia = 'Probabilidade e Estatística', topico = 'Combinatória', subtopico = 'Análise combinatória com restrições' WHERE id = 1280;
UPDATE questoes SET materia = 'Física', topico = 'Funções Afim/Quadrática/Exponencial/Logarítmica/Modular', subtopico = 'Conversão de escalas termométricas (física aplicada)' WHERE id = 1281;
UPDATE questoes SET materia = 'Física', topico = 'Eletrodinâmica', subtopico = 'Análise de circuitos elétricos e correntes' WHERE id = 1282;
UPDATE questoes SET materia = 'Física', topico = 'Relações Fundamentais', subtopico = 'Reatância capacitiva e corrente alternada' WHERE id = 1283;
UPDATE questoes SET materia = 'Física', topico = 'Eletrostática', subtopico = 'Trabalho e energia potencial elétrica' WHERE id = 1284;
UPDATE questoes SET materia = 'Física', topico = 'Eletromagnetismo', subtopico = 'Lei de Ampère e fluxo magnético' WHERE id = 1285;
UPDATE questoes SET materia = 'Física', topico = 'Eletromagnetismo', subtopico = 'Força magnética sobre partícula carregada' WHERE id = 1286;
UPDATE questoes SET materia = 'Física', topico = 'Eletrodinâmica', subtopico = 'Cálculo de corrente elétrica em circuitos lineares' WHERE id = 1287;
UPDATE questoes SET materia = 'Física', topico = 'Grandezas e Medidas', subtopico = 'Unidades do Sistema Internacional (SI)' WHERE id = 1288;
UPDATE questoes SET materia = 'Física', topico = 'Termodinâmica', subtopico = 'Dilatação térmica e refrigeração de motores' WHERE id = 1289;
UPDATE questoes SET materia = 'Física', topico = 'Mecânica', subtopico = 'Trabalho realizado por força constante e variável' WHERE id = 1290;
UPDATE questoes SET materia = 'Física', topico = 'Ondulatória', subtopico = 'Frequência fundamental em cordas vibrantes' WHERE id = 1291;
UPDATE questoes SET materia = 'Física', topico = 'Óptica', subtopico = 'Lentes esféricas e formação de imagens' WHERE id = 1292;
UPDATE questoes SET materia = 'Física', topico = 'Ondulatória', subtopico = 'Velocidade de propagação e frequência em cordas' WHERE id = 1293;
UPDATE questoes SET materia = 'Física', topico = 'Óptica', subtopico = 'Velocidade relativa em espelhos planos' WHERE id = 1294;
UPDATE questoes SET materia = 'Física', topico = 'Óptica', subtopico = 'Convergência de raios solares em espelho côncavo' WHERE id = 1295;
UPDATE questoes SET materia = 'Inglês', topico = 'Interpretação de Texto', subtopico = 'Reading Comprehension' WHERE id = 1296;
UPDATE questoes SET materia = 'Geometria Plana', topico = 'Polígonos', subtopico = 'Teoria dos conjuntos aplicada a quadriláteros planos' WHERE id = 1297;
UPDATE questoes SET materia = 'Álgebra', topico = 'Funções', subtopico = 'Função exponencial e geometria de circunferências' WHERE id = 1298;
UPDATE questoes SET materia = 'Trigonometria', topico = 'Equações Trigonométricas', subtopico = 'Identidades e resolução de equações com arcos múltiplos' WHERE id = 1299;
UPDATE questoes SET materia = 'Álgebra', topico = 'Expressões Algébricas', subtopico = 'Simplificação de expressões numéricas' WHERE id = 1300;
UPDATE questoes SET materia = 'Geometria Plana', topico = 'Áreas de Figuras Planas', subtopico = 'Área de regiões circulares após dobras geométricas' WHERE id = 1301;
UPDATE questoes SET materia = 'Álgebra', topico = 'Questão Incompleta', subtopico = 'Não aplicável devido a OCR incompleto' WHERE id = 1302;
UPDATE questoes SET materia = 'Álgebra', topico = 'Funções', subtopico = 'Propriedades de funções estritamente decrescentes' WHERE id = 1303;
UPDATE questoes SET materia = 'Álgebra Linear', topico = 'Matrizes', subtopico = 'Multiplicação de matrizes e determinantes' WHERE id = 1304;
UPDATE questoes SET materia = 'Polinômios e Complexos', topico = 'Números Complexos', subtopico = 'Módulo, argumento e lugares geométricos no plano complexo' WHERE id = 1305;
UPDATE questoes SET materia = 'Álgebra', topico = 'Equações Irracionais', subtopico = 'Resolução de equações com radicais e divisores de um número' WHERE id = 1306;
UPDATE questoes SET materia = 'Álgebra', topico = 'Logaritmos', subtopico = 'Mudança de base e propriedades operatórias' WHERE id = 1307;
UPDATE questoes SET materia = 'Geometria Analítica', topico = 'Retas', subtopico = 'Equação da reta e quadriláteros circunscritos' WHERE id = 1308;
UPDATE questoes SET materia = 'Geometria Espacial', topico = 'Pirâmides', subtopico = 'Volume do tetraedro e planos perpendiculares' WHERE id = 1309;
UPDATE questoes SET materia = 'Trigonometria', topico = 'Identidades', subtopico = 'Relações trigonométricas em triângulos e lei dos cossenos/senos' WHERE id = 1310;
UPDATE questoes SET materia = 'Geometria Plana', topico = 'Triângulos', subtopico = 'Triângulos isósceles, perímetro e relações métricas' WHERE id = 1311;
UPDATE questoes SET materia = 'Álgebra', topico = 'Funções', subtopico = 'Equação funcional' WHERE id = 1312;
UPDATE questoes SET materia = 'Álgebra', topico = 'Funções', subtopico = 'Equação funcional e recorrência' WHERE id = 1313;
UPDATE questoes SET materia = 'Álgebra', topico = 'Funções', subtopico = 'Propriedades algébricas de funções' WHERE id = 1314;
UPDATE questoes SET materia = 'Álgebra', topico = 'Funções', subtopico = 'Manipulação algébrica e isolamento de variáveis' WHERE id = 1315;
UPDATE questoes SET materia = 'Álgebra', topico = 'Funções', subtopico = 'Avaliação de funções' WHERE id = 1316;
UPDATE questoes SET materia = 'Álgebra', topico = 'Funções', subtopico = 'Relação de recorrência linear' WHERE id = 1317;
UPDATE questoes SET materia = 'Álgebra', topico = 'Funções', subtopico = 'Relação de recorrência linear' WHERE id = 1318;
UPDATE questoes SET materia = 'Álgebra', topico = 'Funções', subtopico = 'Relação de recorrência quadrática' WHERE id = 1319;
UPDATE questoes SET materia = 'Álgebra', topico = 'Funções', subtopico = 'Equação funcional com condições iniciais' WHERE id = 1320;
UPDATE questoes SET materia = 'Álgebra', topico = 'Funções', subtopico = 'Avaliação de funções com condição inicial' WHERE id = 1321;
UPDATE questoes SET materia = 'Álgebra', topico = 'Inequações', subtopico = 'Inequação racional' WHERE id = 1322;
UPDATE questoes SET materia = 'Álgebra', topico = 'Progressões', subtopico = 'Progressão Geométrica e Progressão Aritmética' WHERE id = 1323;
UPDATE questoes SET materia = 'Álgebra Linear', topico = 'Determinantes', subtopico = 'Propriedades de determinantes de matrizes inversíveis' WHERE id = 1324;
UPDATE questoes SET materia = 'Álgebra', topico = 'Funções', subtopico = 'Problemas práticos e razões e proporções' WHERE id = 1325;
UPDATE questoes SET materia = 'Geometria Analítica', topico = 'Cônicas', subtopico = 'Circunferência no plano e distância ao centro' WHERE id = 1326;
UPDATE questoes SET materia = 'Cálculo', topico = 'Limites', subtopico = 'Continuidade de funções e limites indeterminados' WHERE id = 1327;
UPDATE questoes SET materia = 'Álgebra', topico = 'Funções', subtopico = 'Função Modular e cálculo de áreas' WHERE id = 1328;
UPDATE questoes SET materia = 'Geometria Analítica', topico = 'Circunferência no Plano', subtopico = 'Retas tangentes e ângulo entre vetores' WHERE id = 1329;
UPDATE questoes SET materia = 'Álgebra', topico = 'Funções', subtopico = 'Máximos e mínimos de função quadrática' WHERE id = 1330;
UPDATE questoes SET materia = 'Geometria Plana', topico = 'Triângulos', subtopico = 'Triângulo retângulo isósceles e Progressão Aritmética' WHERE id = 1331;
UPDATE questoes SET materia = 'Álgebra', topico = 'Funções', subtopico = 'Funções compostas e lei geral de recorrência' WHERE id = 1332;
UPDATE questoes SET materia = 'Trigonometria', topico = 'Identidades', subtopico = 'Funções trigonométricas inversas e raízes' WHERE id = 1333;
UPDATE questoes SET materia = 'Probabilidade e Estatística', topico = 'Conjuntos', subtopico = 'Operações com conjuntos e diagramas de Venn' WHERE id = 1334;
UPDATE questoes SET materia = 'Álgebra Linear', topico = 'Determinantes', subtopico = 'Determinante de matrizes com parâmetros' WHERE id = 1335;
UPDATE questoes SET materia = 'Trigonometria', topico = 'Identidades', subtopico = 'Relações fundamentais com secante e tangente' WHERE id = 1336;
UPDATE questoes SET materia = 'Trigonometria', topico = 'Triângulos Retângulos e Oblicuângulos', subtopico = 'Lei dos Senos e resolução de triângulos' WHERE id = 1337;
UPDATE questoes SET materia = 'Geometria Analítica', topico = 'Cônicas', subtopico = 'Circunferência de Apolônio e lugares geométricos' WHERE id = 1338;
UPDATE questoes SET materia = 'Álgebra', topico = 'Grandezas Proporcionais', subtopico = 'Regra de três composta' WHERE id = 1339;
UPDATE questoes SET materia = 'Probabilidade e Estatística', topico = 'Combinatória', subtopico = 'Princípio fundamental da contagem e arranjos' WHERE id = 1340;
UPDATE questoes SET materia = 'Geometria Espacial', topico = 'Cones', subtopico = 'Relações métricas no cone circular reto' WHERE id = 1341;
UPDATE questoes SET materia = 'Álgebra Linear', topico = 'Espaços Vetoriais', subtopico = 'Produto vetorial e matrizes' WHERE id = 1342;
UPDATE questoes SET materia = 'Cálculo', topico = 'Limites', subtopico = 'Assíntotas horizontais' WHERE id = 1343;
UPDATE questoes SET materia = 'Cálculo', topico = 'Integrais', subtopico = 'Integração indefinida por substituição' WHERE id = 1344;
UPDATE questoes SET materia = 'Álgebra', topico = 'Razão e Proporção', subtopico = 'Porcentagem e aumentos sucessivos' WHERE id = 1345;
UPDATE questoes SET materia = 'Geometria Espacial', topico = 'Pirâmides', subtopico = 'Tronco de pirâmide regular e área lateral' WHERE id = 1346;
UPDATE questoes SET materia = 'Álgebra', topico = 'Inequações', subtopico = 'Inequações do segundo grau' WHERE id = 1347;
UPDATE questoes SET materia = 'Cálculo', topico = 'Integrais', subtopico = 'Integral definida' WHERE id = 1348;
UPDATE questoes SET materia = 'Polinômios e Complexos', topico = 'Polinômios', subtopico = 'Divisão de polinômios' WHERE id = 1349;
UPDATE questoes SET materia = 'Trigonometria', topico = 'Identidades', subtopico = 'Relações trigonométricas fundamentais' WHERE id = 1350;
UPDATE questoes SET materia = 'Probabilidade e Estatística', topico = 'Probabilidade', subtopico = 'Probabilidade condicional e binomial' WHERE id = 1351;
UPDATE questoes SET materia = 'Álgebra', topico = 'Progressões', subtopico = 'Soma de PG infinita' WHERE id = 1352;
UPDATE questoes SET materia = 'Álgebra', topico = 'Funções', subtopico = 'Domínio de funções reais' WHERE id = 1353;
UPDATE questoes SET materia = 'Álgebra', topico = 'Progressões', subtopico = 'Progressão aritmética' WHERE id = 1354;
UPDATE questoes SET materia = 'Álgebra', topico = 'Funções', subtopico = 'Função composta' WHERE id = 1355;
UPDATE questoes SET materia = 'Cálculo', topico = 'Limites', subtopico = 'Limites indeterminados' WHERE id = 1356;
UPDATE questoes SET materia = 'Geometria Plana', topico = 'Triângulos', subtopico = 'Relações métricas no triângulo retângulo' WHERE id = 1357;
UPDATE questoes SET materia = 'Geometria Analítica', topico = 'Planos', subtopico = 'Equação geral do plano e perpendicularidade' WHERE id = 1358;
UPDATE questoes SET materia = 'Álgebra', topico = 'Conjuntos', subtopico = 'Teoria dos conjuntos e cardinalidade' WHERE id = 1359;
UPDATE questoes SET materia = 'Polinômios e Complexos', topico = 'Números Complexos', subtopico = 'Raiz quadrada de número complexo' WHERE id = 1360;
UPDATE questoes SET materia = 'Polinômios e Complexos', topico = 'Polinômios', subtopico = 'Relações de Girard' WHERE id = 1361;
UPDATE questoes SET materia = 'Álgebra', topico = 'Funções', subtopico = 'Imagem de função racional' WHERE id = 1362;
UPDATE questoes SET materia = 'Probabilidade e Estatística', topico = 'Probabilidade', subtopico = 'Espaço amostral e eventos' WHERE id = 1363;
UPDATE questoes SET materia = 'Cálculo', topico = 'Limites', subtopico = 'Limites fundamentais' WHERE id = 1364;
UPDATE questoes SET materia = 'Geometria Espacial', topico = 'Esferas', subtopico = 'Áreas e volumes de sólidos geométricos' WHERE id = 1365;
UPDATE questoes SET materia = 'Geometria Plana', topico = 'Triângulos', subtopico = 'Perímetro e semelhança de triângulos' WHERE id = 1366;
UPDATE questoes SET materia = 'Álgebra', topico = 'Progressões', subtopico = 'Progressão Geométrica aplicada a misturas' WHERE id = 1367;
UPDATE questoes SET materia = 'Polinômios e Complexos', topico = 'Polinômios', subtopico = 'Relações de Girard e raízes irracionais' WHERE id = 1368;
UPDATE questoes SET materia = 'Polinômios e Complexos', topico = 'Números Complexos', subtopico = 'Forma trigonométrica e desigualdade modular' WHERE id = 1369;
UPDATE questoes SET materia = 'Geometria Analítica', topico = 'Circunferência no Plano', subtopico = 'Posição relativa entre circunferências' WHERE id = 1370;
UPDATE questoes SET materia = 'Álgebra', topico = 'Funções Afim/Quadrática/Exponencial/Logarítmica/Modular', subtopico = 'Função quadrática aplicada a lucro e receita' WHERE id = 1371;
UPDATE questoes SET materia = 'Geometria Analítica', topico = 'Retas', subtopico = 'Distância de ponto a reta e altura de triângulo' WHERE id = 1372;
UPDATE questoes SET materia = 'Cálculo', topico = 'Integrais', subtopico = 'Integração por substituição trigonométrica' WHERE id = 1373;
UPDATE questoes SET materia = 'Álgebra', topico = 'Progressões', subtopico = 'Progressão Geométrica' WHERE id = 1374;
UPDATE questoes SET materia = 'Geometria Plana', topico = 'Circunferência Plana', subtopico = 'Comprimento de arco e área de triângulo' WHERE id = 1375;
UPDATE questoes SET materia = 'Geometria Plana', topico = 'Circunferência Plana', subtopico = 'Círculos concêntricos e cordas' WHERE id = 1376;
UPDATE questoes SET materia = 'Geometria Analítica', topico = 'Cônicas: Elipse, Hipérbole, Parábola', subtopico = 'Identificação de elipse e seus focos' WHERE id = 1377;
UPDATE questoes SET materia = 'Álgebra', topico = 'Funções Afim/Quadrática/Exponencial/Logarítmica/Modular', subtopico = 'Equações do segundo grau com números consecutivos' WHERE id = 1378;
UPDATE questoes SET materia = 'Polinômios e Complexos', topico = 'Polinômios', subtopico = 'Raízes múltiplas e teorema do resto' WHERE id = 1379;
UPDATE questoes SET materia = 'Geometria Analítica', topico = 'Circunferência no Plano', subtopico = 'Intersecção entre circunferências' WHERE id = 1380;
UPDATE questoes SET materia = 'Álgebra', topico = 'Funções Afim/Quadrática/Exponencial/Logarítmica/Modular', subtopico = 'Função composta' WHERE id = 1381;
UPDATE questoes SET materia = 'Probabilidade e Estatística', topico = 'Probabilidade', subtopico = 'Probabilidade geométrica com sólidos' WHERE id = 1382;
UPDATE questoes SET materia = 'Polinômios e Complexos', topico = 'Polinômios', subtopico = 'Teorema Fundamental da Álgebra e raízes complexas' WHERE id = 1383;
UPDATE questoes SET materia = 'Cálculo', topico = 'Integrais', subtopico = 'Integração indefinida por substituição' WHERE id = 1384;
UPDATE questoes SET materia = 'Geometria Espacial', topico = 'Pirâmides', subtopico = 'Volume de pirâmide delimitada por planos cartesianos' WHERE id = 1385;
UPDATE questoes SET materia = 'Probabilidade e Estatística', topico = 'Combinatória', subtopico = 'Probabilidade com permutações e restrições' WHERE id = 1386;
UPDATE questoes SET materia = 'Probabilidade e Estatística', topico = 'Análise Combinatória', subtopico = 'Permutação com restrições de posições alternadas' WHERE id = 1387;
UPDATE questoes SET materia = 'Cálculo', topico = 'Limites', subtopico = 'Continuidade de funções e limites fundamentais' WHERE id = 1388;
UPDATE questoes SET materia = 'Cálculo', topico = 'Limites', subtopico = 'Continuidade e limites no infinito' WHERE id = 1389;
UPDATE questoes SET materia = 'Geometria Analítica', topico = 'Planos', subtopico = 'Equação do plano mediador entre pontos' WHERE id = 1390;
UPDATE questoes SET materia = 'Álgebra Linear', topico = 'Determinantes', subtopico = 'Cálculo de determinantes de matrizes de ordem n' WHERE id = 1391;
UPDATE questoes SET materia = 'Geometria Analítica', topico = 'Vetores', subtopico = 'Produto misto e volume de paralelepípedo' WHERE id = 1392;
UPDATE questoes SET materia = 'Probabilidade e Estatística', topico = 'Estatística', subtopico = 'Diagramas de Venn e contagem de conjuntos' WHERE id = 1393;
UPDATE questoes SET materia = 'Probabilidade e Estatística', topico = 'Probabilidade', subtopico = 'Paradoxo de Monty Hall e probabilidade condicional' WHERE id = 1394;
UPDATE questoes SET materia = 'Probabilidade e Estatística', topico = 'Análise Combinatória', subtopico = 'Princípio fundamental da contagem e permutações' WHERE id = 1395;
UPDATE questoes SET materia = 'Probabilidade e Estatística', topico = 'Probabilidade', subtopico = 'Probabilidade em elementos de poliedros de Platão' WHERE id = 1396;
UPDATE questoes SET materia = 'Probabilidade e Estatística', topico = 'Probabilidade', subtopico = 'Distribuição Binomial e eventos complementares' WHERE id = 1397;
UPDATE questoes SET materia = 'Geometria Plana', topico = 'Circunferência Plana', subtopico = 'Círculos inscritos e circunscritos em triângulo equilátero' WHERE id = 1398;
UPDATE questoes SET materia = 'Polinômios e Complexos', topico = 'Polinômios', subtopico = 'Relações de Girard e somas de potências de raízes' WHERE id = 1399;
UPDATE questoes SET materia = 'Cálculo', topico = 'Integrais', subtopico = 'Cálculo de área entre curvas por integral definida' WHERE id = 1400;
UPDATE questoes SET materia = 'Álgebra', topico = 'Razão e Proporção', subtopico = 'Sistemas de equações com razões' WHERE id = 1401;
UPDATE questoes SET materia = 'Geometria Analítica', topico = 'Retas', subtopico = 'Projeção ortogonal de ponto sobre reta no plano' WHERE id = 1402;
UPDATE questoes SET materia = 'Álgebra Linear', topico = 'Matrizes', subtopico = 'Multiplicação de matrizes e codificação' WHERE id = 1403;
UPDATE questoes SET materia = 'Cálculo', topico = 'Derivadas', subtopico = 'Equação da reta tangente a uma curva' WHERE id = 1404;
UPDATE questoes SET materia = 'Álgebra', topico = 'Funções', subtopico = 'Equação funcional' WHERE id = 1405;
UPDATE questoes SET materia = 'Probabilidade e Estatística', topico = 'Análise Combinatória', subtopico = 'Teoria dos Grafos e combinatória extremal' WHERE id = 1406;
UPDATE questoes SET materia = 'Cálculo', topico = 'Limites', subtopico = 'Continuidade de Funções' WHERE id = 1407;
UPDATE questoes SET materia = 'Geometria Plana', topico = 'Triângulos', subtopico = 'Bissetrizes e Ângulos no Triângulo' WHERE id = 1408;
UPDATE questoes SET materia = 'Cálculo', topico = 'Limites', subtopico = 'Limites no Infinito' WHERE id = 1409;
UPDATE questoes SET materia = 'Cálculo', topico = 'Derivadas', subtopico = 'Regra da Cadeia' WHERE id = 1410;
UPDATE questoes SET materia = 'Cálculo', topico = 'Derivadas', subtopico = 'Máximos e Mínimos' WHERE id = 1411;
UPDATE questoes SET materia = 'Álgebra', topico = 'Funções', subtopico = 'Função Composta e Quadrática' WHERE id = 1412;
UPDATE questoes SET materia = 'Álgebra', topico = 'Teoria dos Números', subtopico = 'Divisibilidade e Congruências' WHERE id = 1413;
UPDATE questoes SET materia = 'Cálculo', topico = 'Derivadas', subtopico = 'Otimização' WHERE id = 1414;
UPDATE questoes SET materia = 'Probabilidade e Estatística', topico = 'Probabilidade', subtopico = 'Probabilidade sem Reposição' WHERE id = 1415;
UPDATE questoes SET materia = 'Probabilidade e Estatística', topico = 'Probabilidade', subtopico = 'Distribuição Binomial' WHERE id = 1416;
UPDATE questoes SET materia = 'Cálculo', topico = 'Integrais', subtopico = 'Integral Definida' WHERE id = 1417;
UPDATE questoes SET materia = 'Cálculo', topico = 'Integrais', subtopico = 'Integração por Substituição' WHERE id = 1418;
UPDATE questoes SET materia = 'Cálculo', topico = 'Derivadas', subtopico = 'Derivadas de Funções Trigonométricas' WHERE id = 1419;
UPDATE questoes SET materia = 'Probabilidade e Estatística', topico = 'Combinatória', subtopico = 'Combinações Simples com Restrição' WHERE id = 1420;
UPDATE questoes SET materia = 'Probabilidade e Estatística', topico = 'Combinatória', subtopico = 'Combinação Completa' WHERE id = 1421;
UPDATE questoes SET materia = 'Álgebra', topico = 'Conjuntos', subtopico = 'Conjuntos Numéricos' WHERE id = 1422;
UPDATE questoes SET materia = 'Álgebra', topico = 'Funções', subtopico = 'Álgebra de Funções' WHERE id = 1423;
UPDATE questoes SET materia = 'Geometria Espacial', topico = 'Prismas', subtopico = 'Razão de Volumes de Cubos' WHERE id = 1424;
UPDATE questoes SET materia = 'Geometria Analítica', topico = 'Retas', subtopico = 'Área de Triângulo no Plano' WHERE id = 1425;
UPDATE questoes SET materia = 'Geometria Plana', topico = 'Circunferência Plana', subtopico = 'Relações métricas na circunferência' WHERE id = 1426;
UPDATE questoes SET materia = 'Geometria Analítica', topico = 'Cônicas', subtopico = 'Elipse' WHERE id = 1427;
UPDATE questoes SET materia = 'Álgebra', topico = 'Equações', subtopico = 'Equações do 2º Grau e Problemas Algébricos' WHERE id = 1428;
UPDATE questoes SET materia = 'Cálculo', topico = 'Limites', subtopico = 'Limites Fundamentais e Indeterminações' WHERE id = 1429;
UPDATE questoes SET materia = 'Álgebra', topico = 'Funções', subtopico = 'Equações Funcionais' WHERE id = 1430;
UPDATE questoes SET materia = 'Álgebra', topico = 'Inequações', subtopico = 'Módulos e Inequações Modulares' WHERE id = 1431;
UPDATE questoes SET materia = 'Probabilidade e Estatística', topico = 'Combinatória', subtopico = 'Binômio de Newton' WHERE id = 1432;
UPDATE questoes SET materia = 'Probabilidade e Estatística', topico = 'Combinatória', subtopico = 'Princípio da Inclusão-Exclusão e Anagramas' WHERE id = 1433;
UPDATE questoes SET materia = 'Geometria Espacial', topico = 'Esferas', subtopico = 'Esfera Inscrita em Pirâmide' WHERE id = 1434;
UPDATE questoes SET materia = 'Trigonometria', topico = 'Funções Trigonométricas', subtopico = 'Gráficos de Funções Seno e Cosseno' WHERE id = 1435;
UPDATE questoes SET materia = 'Geometria Plana', topico = 'Circunferência Plana', subtopico = 'Áreas de Figuras Planas e Intersecção de Circunferências' WHERE id = 1436;
UPDATE questoes SET materia = 'Cálculo', topico = 'Derivadas', subtopico = 'Funções Injetivas e Aplicações da Derivada' WHERE id = 1437;
UPDATE questoes SET materia = 'Geometria Analítica', topico = 'Planos', subtopico = 'Simetria em Relação a Planos' WHERE id = 1438;
UPDATE questoes SET materia = 'Álgebra', topico = 'Inequações', subtopico = 'Inequações Quociente e Produto com Módulo' WHERE id = 1439;
UPDATE questoes SET materia = 'Polinômios e Complexos', topico = 'Números Complexos', subtopico = 'Potências de i e Somatórios' WHERE id = 1440;
UPDATE questoes SET materia = 'Geometria Plana', topico = 'Triângulos', subtopico = 'Pontos Notáveis do Triângulo (Incentro e Circuncentro)' WHERE id = 1441;
UPDATE questoes SET materia = 'Geometria Espacial', topico = 'Esferas', subtopico = 'Esferas Tangentes e Cubo' WHERE id = 1442;
UPDATE questoes SET materia = 'Cálculo', topico = 'Sequências e Séries', subtopico = 'Séries Telescópicas' WHERE id = 1443;
UPDATE questoes SET materia = 'Geometria Analítica', topico = 'Vetores', subtopico = 'Produto Escalar em R3' WHERE id = 1444;
UPDATE questoes SET materia = 'Cálculo', topico = 'Limites', subtopico = 'Continuidade e Limites Laterais' WHERE id = 1445;
UPDATE questoes SET materia = 'Cálculo', topico = 'Integrais', subtopico = 'Integrais Impróprias e Sólidos de Revolução' WHERE id = 1446;
UPDATE questoes SET materia = 'Álgebra Linear', topico = 'Determinantes', subtopico = 'Cálculo de Determinante de Matriz de Vandermonde' WHERE id = 1447;